-- =============================================================================
-- Plataforma de Gestao de Talentos IT - Grupo BC5
-- Script de criacao da base de dados PostgreSQL
-- =============================================================================
-- Equivalente as migrations EF Core ate ao Sprint 6.
-- Para correr: psql -d TalentosDB -f database/schema.sql
-- =============================================================================

-- =============================================================================
-- Tabelas independentes (sem chaves estrangeiras)
-- =============================================================================

CREATE TABLE IF NOT EXISTS "Areas" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome"      text NOT NULL,
    "CriadoEm"  timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Areas_Nome" ON "Areas" ("Nome");

CREATE TABLE IF NOT EXISTS "Users" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username"      text NOT NULL,
    "Password"      text NOT NULL,
    "Role"          integer NOT NULL,
    "EstadoConta"   integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "Logs" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CommandName"   text NOT NULL,
    "EntityName"    text NOT NULL,
    "EntityType"    text NOT NULL,
    "EntityId"      integer NOT NULL,
    "UserId"        integer NOT NULL,
    "Username"      text NOT NULL,
    "OldValues"     text NULL,
    "NewValues"     text NULL,
    "Date"          timestamp with time zone NOT NULL
);

-- =============================================================================
-- Tabelas com FK para Users / Areas
-- =============================================================================

CREATE TABLE IF NOT EXISTS "Clientes" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome"          text NOT NULL,
    "Email"         text NOT NULL,
    "IdCriador"     integer NOT NULL,
    "IdMinhaConta"  integer NULL,
    CONSTRAINT "FK_Clientes_Users_IdCriador"
        FOREIGN KEY ("IdCriador") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_Clientes_IdCriador" ON "Clientes" ("IdCriador");

CREATE TABLE IF NOT EXISTS "Skills" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome"          character varying(100) NOT NULL,
    "AreaId"        integer NOT NULL,
    "CriadoEm"      timestamp with time zone NOT NULL,
    "AtualizadoEm"  timestamp with time zone NOT NULL,
    CONSTRAINT "FK_Skills_Areas_AreaId"
        FOREIGN KEY ("AreaId") REFERENCES "Areas" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Skills_Nome" ON "Skills" ("Nome");
CREATE INDEX IF NOT EXISTS "IX_Skills_AreaId" ON "Skills" ("AreaId");

CREATE TABLE IF NOT EXISTS "Perfis" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome"          text NOT NULL,
    "Email"         text NOT NULL,
    "Pais"          text NOT NULL,
    "PrecoPorHora"  numeric NOT NULL,
    "OwnerId"       integer NOT NULL,
    "IsShared"      boolean NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    CONSTRAINT "FK_Perfis_Users_OwnerId"
        FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Perfis_OwnerId" ON "Perfis" ("OwnerId");

-- =============================================================================
-- Tabelas dependentes de Perfis / Skills
-- =============================================================================

CREATE TABLE IF NOT EXISTS "ExperienciasProfissionais" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Titulo"    text NOT NULL,
    "Empresa"   text NOT NULL,
    "AnoInicio" integer NOT NULL,
    "AnoFim"    integer NULL,
    "PerfilId"  integer NOT NULL,
    CONSTRAINT "FK_ExperienciasProfissionais_Perfis_PerfilId"
        FOREIGN KEY ("PerfilId") REFERENCES "Perfis" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_ExperienciasProfissionais_PerfilId"
    ON "ExperienciasProfissionais" ("PerfilId");

CREATE TABLE IF NOT EXISTS "PerfilSkills" (
    "PerfilId"          integer NOT NULL,
    "SkillId"           integer NOT NULL,
    "AnosExperiencia"   integer NOT NULL,
    CONSTRAINT "PK_PerfilSkills" PRIMARY KEY ("PerfilId", "SkillId"),
    CONSTRAINT "FK_PerfilSkills_Perfis_PerfilId"
        FOREIGN KEY ("PerfilId") REFERENCES "Perfis" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PerfilSkills_Skills_SkillId"
        FOREIGN KEY ("SkillId") REFERENCES "Skills" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_PerfilSkills_SkillId" ON "PerfilSkills" ("SkillId");

-- =============================================================================
-- Propostas e tabelas associadas
-- =============================================================================

CREATE TABLE IF NOT EXISTS "Propostas" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome"                  character varying(200) NOT NULL,
    "AreaId"                integer NOT NULL,
    "DescricaoTrabalho"     character varying(2000) NOT NULL,
    "NumeroTotalHoras"      integer NOT NULL,
    "PrecoHoraMedio"        numeric NOT NULL,
    "Estado"                integer NOT NULL DEFAULT 0,
    "CriadorId"             integer NULL,
    "TalentoSelecionadoId"  integer NULL,
    "CriadoEm"              timestamp with time zone NOT NULL,
    "AtualizadoEm"          timestamp with time zone NOT NULL,
    CONSTRAINT "FK_Propostas_Areas_AreaId"
        FOREIGN KEY ("AreaId") REFERENCES "Areas" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Propostas_Users_CriadorId"
        FOREIGN KEY ("CriadorId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Propostas_Nome" ON "Propostas" ("Nome");
CREATE INDEX IF NOT EXISTS "IX_Propostas_AreaId" ON "Propostas" ("AreaId");
CREATE INDEX IF NOT EXISTS "IX_Propostas_CriadorId" ON "Propostas" ("CriadorId");

CREATE TABLE IF NOT EXISTS "SkillsNecessarias" (
    "Id"                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PropostaId"             integer NOT NULL,
    "SkillId"                integer NOT NULL,
    "NivelMinimoRequerido"   integer NOT NULL,
    "CriadoEm"               timestamp with time zone NOT NULL,
    CONSTRAINT "FK_SkillsNecessarias_Propostas_PropostaId"
        FOREIGN KEY ("PropostaId") REFERENCES "Propostas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SkillsNecessarias_Skills_SkillId"
        FOREIGN KEY ("SkillId") REFERENCES "Skills" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_SkillsNecessarias_PropostaId"
    ON "SkillsNecessarias" ("PropostaId");
CREATE INDEX IF NOT EXISTS "IX_SkillsNecessarias_SkillId"
    ON "SkillsNecessarias" ("SkillId");

CREATE TABLE IF NOT EXISTS "TalentosElegiveis" (
    "Id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PropostaId"     integer NOT NULL,
    "PerfilId"       integer NOT NULL,
    "ValorEstimado"  numeric NOT NULL,
    "CriadoEm"       timestamp with time zone NOT NULL,
    CONSTRAINT "FK_TalentosElegiveis_Propostas_PropostaId"
        FOREIGN KEY ("PropostaId") REFERENCES "Propostas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TalentosElegiveis_Perfis_PerfilId"
        FOREIGN KEY ("PerfilId") REFERENCES "Perfis" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_TalentosElegiveis_PropostaId"
    ON "TalentosElegiveis" ("PropostaId");
CREATE INDEX IF NOT EXISTS "IX_TalentosElegiveis_PerfilId"
    ON "TalentosElegiveis" ("PerfilId");

CREATE TABLE IF NOT EXISTS "PartilhaTokens" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Token"       text NOT NULL,
    "PropostaId"  integer NOT NULL,
    "CriadoEm"    timestamp with time zone NOT NULL,
    "ExpiraEm"    timestamp with time zone NULL,
    CONSTRAINT "FK_PartilhaTokens_Propostas_PropostaId"
        FOREIGN KEY ("PropostaId") REFERENCES "Propostas" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_PartilhaTokens_Token" ON "PartilhaTokens" ("Token");
CREATE INDEX IF NOT EXISTS "IX_PartilhaTokens_PropostaId" ON "PartilhaTokens" ("PropostaId");

-- =============================================================================
-- Fim do schema
-- =============================================================================
