// <auto-generated />
using System;
using GestaoTalentos.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoTalentos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417165234_AddPerfisAndPropostasAndTalentosElegiveis")]
    partial class AddPerfisAndPropostasAndTalentosElegiveis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoTalentos.Domain.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.Proposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoTrabalho")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumeroTotalHoras")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoHoraMedio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Propostas");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.SkillNecessaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NivelMinimoRequerido")
                        .HasColumnType("integer");

                    b.Property<int>("PropostaId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillsNecessarias");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.TalentoElegivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<int>("PropostaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("PropostaId");

                    b.ToTable("TalentosElegiveis");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.Proposta", b =>
                {
                    b.HasOne("GestaoTalentos.Domain.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.Skill", b =>
                {
                    b.HasOne("GestaoTalentos.Domain.Area", "Area")
                        .WithMany("Skills")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.SkillNecessaria", b =>
                {
                    b.HasOne("GestaoTalentos.Domain.Proposta", null)
                        .WithMany("SkillsNecessarias")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoTalentos.Domain.Skill", "Skill")
                        .WithMany("SkillsNecessarias")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.TalentoElegivel", b =>
                {
                    b.HasOne("GestaoTalentos.Domain.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoTalentos.Domain.Proposta", "Proposta")
                        .WithMany("TalentosElegiveis")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.Area", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.Proposta", b =>
                {
                    b.Navigation("SkillsNecessarias");

                    b.Navigation("TalentosElegiveis");
                });

            modelBuilder.Entity("GestaoTalentos.Domain.Skill", b =>
                {
                    b.Navigation("SkillsNecessarias");
                });
#pragma warning restore 612, 618
        }
    }
}
